# Generated by Django 5.1.4 on 2025-01-11 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_alter_status_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='creator',
        ),
    ]
